# Site settings
title: Bruce Caraway
email: bruce.caraway@gmail.com
description: Bruce's personal blog
baseurl: ''
url: "http://brucecaraway.com" # the base hostname & protocol for your site
twitter_username: brucecaraway
instagram_id: 700784

paginate: 5

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Bruce
      layout: "post"
      category: news
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      author: Bruce 
      layout: "page"
